# Generated by Django 5.0 on 2024-12-08 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NeutritionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "neu_f_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "neu_l_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                ("neu_id", models.IntegerField(unique=True, verbose_name="ID")),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Dinajpur", "Dinajpur"),
                            ("Bogura", "Bogura"),
                            ("Rajshahi", "Rajshahi"),
                            ("Chottogram", "Chottogram"),
                            ("Sylhet", "Sylhet"),
                        ],
                        default="Dinajpur",
                        max_length=20,
                        verbose_name="Location",
                    ),
                ),
                (
                    "produce",
                    models.CharField(
                        choices=[
                            ("Potato", "Potato"),
                            ("Cucumber", "Cucumber"),
                            ("Tomato", "Tomato"),
                            ("Cabbage", "Cabbage"),
                            ("Onion", "Onion"),
                        ],
                        default="Potato",
                        max_length=20,
                        verbose_name="Food Selection",
                    ),
                ),
                (
                    "applicable_temperature",
                    models.FloatField(default=10.0, verbose_name="Temperature (°C)"),
                ),
                (
                    "applicable_humidity",
                    models.FloatField(default=50.0, verbose_name="Humidity (%)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeedRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farmer_full_name", models.CharField(max_length=100)),
                ("farmer_id", models.IntegerField()),
                ("seed_variety", models.CharField(max_length=100)),
                ("other_seed_name", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seller_name", models.CharField(max_length=100)),
                ("seller_id", models.IntegerField(unique=True)),
                ("contact_phone", models.CharField(max_length=15)),
                ("contact_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("quantity", models.FloatField()),
                ("description", models.TextField(blank=True)),
                ("required_temperature", models.FloatField()),
                ("required_humidity", models.FloatField()),
                (
                    "warehouse_location",
                    models.CharField(
                        choices=[
                            ("Dhaka", "Dhaka"),
                            ("Bogura", "Bogura"),
                            ("Chottogram", "Chottogram"),
                        ],
                        max_length=50,
                    ),
                ),
                ("available_quantity", models.FloatField()),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="dashboard.seller",
                    ),
                ),
            ],
        ),
    ]
